### ISSUE TITLE
Use Version objects for solc versions

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [iamdefinitelyahuman/py-solc-x#17]
### Overview
Use `Version` objects to represent solc versions, instead of strings.

### Specification
1. `solcx/install.py` - store the `solc_version` variable as a `Version` and update related code.
2. Return `Version` object(s) anywhere a version is returned to a user, e.g. `get_available_solc_versions` and `get_installed_solc_versions`
3. All functions receiving a version in the user input should be able to understand both strings and `Version` objects, e.g. `set_solc_version`, `install_solc`
4. Remove the `get_solc_version_string` method (this information is still available from `get_solc_version`).
5. Update unit tests to ensure all new/modified code is adequately covered.

### References
* [`semantic_version` docs: the `Version` class](https://python-semanticversion.readthedocs.io/en/latest/reference.html#representing-a-version-the-version-class)

### Dependencies
This will amount to a breaking change, so cannot happen until `1.0.0`.

**Comment by carlfarterson** [comment]
I got this
