### ISSUE TITLE
Failed to install on Mac

### ISSUE THREAD

**Issue by Skyge** [iamdefinitelyahuman/py-solc-x#47]
This is my first time to use this package, so I just write a simple code like the doc to have a try, like this:
```python
from solcx import install_solc
install_solc('v0.5.12')
```
It is ok at the beginning, but later, it failed to install, the error message is:
```js
[ 79%] Building CXX object test/CMakeFiles/soltest.dir/libsolidity/SolidityCompiler.cpp.o
[ 79%] Building CXX object test/CMakeFiles/soltest.dir/libsolidity/SolidityEndToEndTest.cpp.o
Traceback (most recent call last):
  File "/Users/skyge/Envs/test_solc/lib/python3.7/site-packages/solcx/install.py", line 359, in _install_solc_osx
    _check_subprocess_call(cmd, message="Running {}".format(cmd[0]))
  File "/Users/skyge/Envs/test_solc/lib/python3.7/site-packages/solcx/install.py", line 254, in _check_subprocess_call
    command, stderr=subprocess.STDOUT if verbose else subprocess.DEVNULL, **proc_kwargs
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_solc_x.py", line 3, in <module>
    install_solc('v0.5.12')
  File "/Users/skyge/Envs/test_solc/lib/python3.7/site-packages/solcx/install.py", line 226, in install_solc
    _install_solc_osx(version, allow_osx, show_progress, solcx_binary_path)
  File "/Users/skyge/Envs/test_solc/lib/python3.7/site-packages/solcx/install.py", line 367, in _install_solc_osx
    "".format(cmd[0], e.returncode)
OSError: make returned non-zero exit status 2 while attempting to build solc from the source. This is likely due to a missing or incorrect version of an external dependency.

You may be able to solve this by installing the specific version using brew: https://solidity.readthedocs.io/en/v0.6.0/installing-solidity.html#binary-packages
```
I am not sure what is wrong with the build, so I follow the recommend: install by the binary-packages, and I run the following commands:

```js
brew update
brew upgrade
brew tap ethereum/ethereum
brew install solidity
```
And `solc --version` can return a value: 
```
solc, the solidity compiler commandline interface
Version: 0.6.4+commit.1dca32f3.Darwin.appleclang
```
So I run that test python file again, unfortunately, I got the same error, so what should I do next?

* `py-solc-x` Version: 0.8.0
* `solc` Version: 3.2.0
* Python Version: Python 3.7.2
* OS: macOS 10.14 Mojave.

**Comment by iamdefinitelyahuman** [comment]
Thanks for letting me know about this.

Unfortunately, building `solc` sometimes relies on a specific and outdated version of `boost`. This creates challenges installing on OSX.

I did not realize the issue extended as recent as `0.5.12` - I am not using OSX, and the last time I tried installation was working for all `0.5.x` versions.

There is a workaround possible via #42 but it requires trusting binaries built by a 3rd party.  I will try to release a new version soon that gives an option to install via this route, which will address your specific case.

**Comment by Skyge** [comment]
Hi, you know I want to use the version of `0.5.12` to compile my contract, so I am recommended to  find a raw file link of the specific commit of `solidity.rb` and run
```
brew unlink solidity
# install 0.5.12
brew install https://raw.githubusercontent.com/ethereum/homebrew-ethereum/4d13060698e7f0cdac9ec24627b6485122b8f1b6/solidity.rb
```
It seems like every version will be installed globally, a little annoying, maybe we can install it as a develop dependency, I don't know if I made it clear.

**Comment by Skyge** [comment]
I am using the frame: [Brownie](https://github.com/iamdefinitelyahuman/brownie) now, and I do not need to install this package separately, so I think we can close this issue.

**Comment by iamdefinitelyahuman** [comment]
Glad to hear!
