### ISSUE TITLE
Dynamic binary package referencing

### ISSUE THREAD

**Issue by carlfarterson** [iamdefinitelyahuman/py-solc-x#60]
### Overview
Currently, `install.py` references Solidity v0.6.0 for installing binaries with a fixed variable.  It would be great to have `CURRENT_RELEASE` dynamically fetch the most-recent binaries.

### Specification
Create a function within `install.py` to fetch the current stable binary packages.

**Comment by iamdefinitelyahuman** [comment]
I can definitely see a use case!

`solc.install_latest_solc_version()` or `solcx.install_solc('latest')` both make sense to me.
