### ISSUE TITLE
arm support / check arch

### ISSUE THREAD

**Issue by step21** [iamdefinitelyahuman/py-solc-x#66]
### Overview
It is easily possible to run most things on arm, or another architecture that is not x86. However solc-x doesn't check for it, doesn't complain and happily downloads the wrong binary, which then results in exec format error. When I copy a manually compile solc into $PATH, it works however.
At the very least, solc-x should check the arch and complain before downloading and running, or alternatively download the right binary accordingly.

### Specification
Ideally, solc-x checks the architecture, and if a corresponding binary is available, downloads that.

**Comment by iamdefinitelyahuman** [comment]
Thanks for bringing this up.

Adding a check shouldn't be difficult.  I don't think the solidity team serves binaries for arm but it should still be possible to build it manually when the correct dependencies are in place. Given `py-solc-x` already does that for OSX, it will (hopefully) be easy to implement for this case.

**Comment by step21** [comment]
It should be pretty similar to how it is done on os x, yes.

**Comment by step21** [comment]
To avoid duplicating code, where do you think would be the best way to put this? Mayb define `_compile_solc` and this then gets called from install_osx and install_arm, which both get called from install_solc, where first arch is checked, and then depending on that it is compiled or if x86, the way used so far is kept. Additionally, maybe check platform, as I do not know if / how much relevance arm has on windows (probably very little) or on MacOS (none).

**Comment by iamdefinitelyahuman** [comment]
Yes, I think we're in agreement with the approach:

* in `install_solc`, prior to the `sys.platform` checks, do a check for the architecture and if not x86, call a new `_install_solc_arm` function
* the majority of code in `_install_solc_osx` can be moved into a `_compile_solc` method that gets called by `_install_solc_osx` and the new `_install_solc_arm`

If there is no additional logic beyond what's needed in `_compile_solc`, you might be able to omit the `_install_solc_arm` function in the middle and just call directly from `install_solc` to `_compile_solc`. 

Admittedly my experience with arm is zero, you're probably more knowledgeable than I in what steps are needed here.  If you want to open a PR I'll be very happy to receive and review it :pray:

**Comment by step21** [comment]
Thanks for the reply. I'll try to get a PR soon.

> Admittedly my experience with arm is zero, you're probably more knowledgeable than I in what steps are needed here.

Assuming dependencies are installed, it is literally the same as on linux.  (I am only talking arm on linux here) Checking dependencies would depend on distribution or running some cmake command (if I remember correctly solc uses cmake)

**Comment by iamdefinitelyahuman** [comment]
Closed in #82
