### ISSUE TITLE
Add install.get_all_available_versions method 

### ISSUE THREAD

**Issue by ritzdorf** [iamdefinitelyahuman/py-solc-x#7]
First of all, thanks for the awesome work.

What is the most efficient way to install all currently supported compiler versions?

So far we were installing all versions between 0.4.11 and "latest", but latest just became 0.4.26:
https://github.com/ethereum/solidity/releases/tag/v0.4.26

Do you have any suggestions?

**Comment by ritzdorf** [comment]
FYI:
We switched the design and are installing solc versions dynamically. We are parsing the available versions out of the GitHub releases page now:
https://api.github.com/repos/ethereum/solidity/releases

https://github.com/eth-sri/securify/blob/ad0150aa9b42cf164d352754cab66b3170c04158/scripts/pysolc.py#L128-L143

Still happy for feedback though.

**Comment by iamdefinitelyahuman** [comment]
My first thought was to do exactly as you're doing and parse the github API.

Perhaps solcx should have  an ``install_all_solc_versions`` method (or some similar name).

**Comment by ritzdorf** [comment]
> Perhaps solcx should have an install_all_solc_versions method (or some similar name).

Yes, or at least a `get_all_available_versions` method. Then installing can be added on top easily.

**Comment by iamdefinitelyahuman** [comment]
Re-opening this issue so it's more immediately on my todo list tomorrow
