### ISSUE TITLE
Provide a direct way to pass a custom solc binary path

### ISSUE THREAD

**Issue by dmuhs** [iamdefinitelyahuman/py-solc-x#76]
### Overview

In some scenarios where I am applying `py-solc-x`, a user might want to specify a solc version that is already set up on their machine. This means that the automatic installation should not be executed.
I have seen that there is the `SOLCX_BINARY_PATH` env var, which allows the user to specify which directory to look in for a solc binary. There is also a platform-specific check using `which` to look for the solc binary on the `PATH`.
When using the library (which is absolutely amazing btw!), I expected a more explicit way. Please consider the following examples.

### Specification
An addition to the compilation parameter set, such as:
```python
solcx.compile_standard(
   ...
   solc_path="/foo/bar/solc"
)
```

This would effectively short-circuit any internal checks looking for the solc binary and simply take over the parameter's location if it has been set. Alternatively, and following the paradigm of explicit module-level calls, an explicit setting outside of a function call can be considered as well:

```python
import solcx
solcx.set_solc_installation("/foo/bar/solc")
```

This would result in a global short circuit of the checking logic and always use the path set with `set_solc_installation`.

At first glance both ways seem to not cause any breaking changes.

**Comment by iamdefinitelyahuman** [comment]
I really like this!  It would essentially reconnect `py-solc-x` with the original `py-solc` by making the installation and version management an optional behavior.
