### ISSUE TITLE
Source mappings have no match on the AST

### ISSUE THREAD

**Issue by WilhelmStein** [iamdefinitelyahuman/py-solc-x#77]
### Environment information

* `py-solc-x` Version: 0.8.2
* `solc` Version: 0.6.8+commit.0bbfe453.Linux.g++
* Python Version: 3.6.9
* OS: Ubuntu 18.04.4 LTS

### What was wrong?
I compiled the [Fomo3D](https://etherscan.io/address/0xa62142888aba8370742be823c1782d17a0389da1#code) contract using the 0.4.24+commit.e67f0147.Linux.g++ solc version. Afterwards, while observing the trace of the following [transaction](https://etherscan.io/tx/0x5c932a5c59f9691ca9f334fe744c00f9aabe64991ade8fea52a6e1b22a793664), I noticed that some source mappings of the bytecode that py-solc-x outputs, have no match on the AST that py-solc-x outputs.

Below are the source mappings that have no match:
```
Could not find ast node from source mapping: 49693 : 37 : 0
Could not find ast node from source mapping: 49693 : 65 : 0
Could not find ast node from source mapping: 49693 : 37 : 0
Could not find ast node from source mapping: 49693 : 65 : 0
Could not find ast node from source mapping: 49693 : 65 : 0
Could not find ast node from source mapping: 15759 : 18 : 0
Could not find ast node from source mapping: 15759 : 18 : 0
Could not find ast node from source mapping: 18654 : 9 : 0
Could not find ast node from source mapping: 46882 : 21 : 0
Could not find ast node from source mapping: 46882 : 30 : 0
Could not find ast node from source mapping: 46882 : 21 : 0
Could not find ast node from source mapping: 46882 : 30 : 0
Could not find ast node from source mapping: 46882 : 30 : 0
Could not find ast node from source mapping: 11308 : 10 : 0
Could not find ast node from source mapping: 11429 : 8 : 0
Could not find ast node from source mapping: 10295 : 42 : 0
```

Note: The above message is not an actual error message, it's simply me annotating what I perceive the mistake to be in the example above.

**Comment by iamdefinitelyahuman** [comment]
Hi,

What are the exact outputs you're generating?  There are two types of AST, maybe you're looking at the legacy one.  It's just a guess though.. I've never run into this issue before.

If you aren't, I'd suggest compiling via the [standard JSON input](https://solidity.readthedocs.io/en/latest/using-the-compiler.html?highlight=ast%20#compiler-input-and-output-json-description) and using the source map and AST returned that way.

**Comment by WilhelmStein** [comment]
I am using the new AST, not the legacy one.

**Comment by iamdefinitelyahuman** [comment]
Can you share the code you're using?  I just compiled the contract source from etherscan, and I'm not seeing any of the offsets you listed in the `deployedSourceMap` or `sourceMap` outputs.

**Comment by WilhelmStein** [comment]
Here's where I got the [code](https://contract-library.com/contracts/Ethereum/0xa62142888aba8370742be823c1782d17a0389da1) from.
Also, the compilation settings I used are the following:
```
{
    'language': 'Solidity',
    'sources': {
        '/tmp/temp.sol': {'urls': ['/tmp/temp.sol']}
    },
    'settings': {
        'optimizer': {'enabled': True, 'runs': 50},
        'outputSelection': {
            '*': {
                '*': ['evm.deployedBytecode.sourceMap', 'evm.deployedBytecode.object'],
                '': ['ast']
            }
        }
    }
}
```

**Comment by iamdefinitelyahuman** [comment]
Yeah, same thing. Compiling with the JSON you give above, and using the source as taken from contract-library, I'm not producing a `sourceMap` that has any of the offsets you mention in the original message.

**Comment by WilhelmStein** [comment]
I found a bug in my code and while it is now fixed and those messages are not being displayed, some others (very few) have taken their place. The whole point of this issue was to ascertain if it would be possible for source mapping mismatches to appear. As far as I understand, such behavior is not to be expected. I'll keep this issue open just in case.

**Comment by iamdefinitelyahuman** [comment]
From my experience, offsets is sometimes missing from the `sourceMap` (https://github.com/ethereum/solidity/issues/9006), but I've never encountered a mismatch when an offset is given.

Not sure if it's useful for you, but here's some code I wrote that does a lot of association between the source map and the AST: [`iamdefinitelyahuman/brownie:brownie/project/compiler/solidity.py`](https://github.com/iamdefinitelyahuman/brownie/blob/master/brownie/project/compiler/solidity.py)

**Comment by WilhelmStein** [comment]
Well, in the same example, I did come across these unmatched mappings, which seem to be invalid.
```
15759 : 18 : 0
18654 :  9 : 0
```
