### ISSUE TITLE
New `solc` release, breaks imports of solcx

### ISSUE THREAD

**Issue by ritzdorf** [iamdefinitelyahuman/py-solc-x#8]
* `py-solc-x` Version: 0.2.1
* `solc` Version: none
* Python Version: 3.6
* OS: Ubuntu

### What was wrong?

Because the current latest release `0.4.26` does not provide a `solc-static-linux` binary yet, all imports of solcx fail, because the `__init__` function will try to install `0.4.26` if no version is installed.

Example:

```
  File "/root/.local/lib/python3.6/site-packages/solcx/__init__.py", line 27, in <module>
    install_solc()
  File "/root/.local/lib/python3.6/site-packages/solcx/install.py", line 83, in install_solc
    _install_solc_linux(version)
  File "/root/.local/lib/python3.6/site-packages/solcx/install.py", line 144, in _install_solc_linux
    _wget(download, binary_path)
  File "/root/.local/lib/python3.6/site-packages/solcx/install.py", line 130, in _wget
    "Downloading solc from {}".format(url)
  File "/root/.local/lib/python3.6/site-packages/solcx/install.py", line 118, in _check_subprocess_call
    **proc_kwargs
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', 'https://github.com/ethereum/solidity/releases/download/v0.4.26/solc-static-linux', '-O', '/root/.local/lib/python3.6/site-packages/solcx/bin/solc-v0.4.26']' returned non-zero exit status 8.
```

Could there be some error handling for this as this seems to happen with every new release?
Thanks.

**Comment by iamdefinitelyahuman** [comment]
Yeah, definitely can add an error handler. Thanks for bringing it to my attention.

Can you confirm - is it typical that a new solidity release doesn't initially include the static binary but adds it shortly after?

**Comment by ritzdorf** [comment]
> is it typical that a new solidity release doesn't initially include the static binary but adds it shortly after?

Yes. That is my personal experience. It often takes a few hours before the static binary is added.

**Comment by iamdefinitelyahuman** [comment]
I've added the ``get_available_solc_versions`` method as discussed in #7. I'm using that to determine which version of ``solc`` to install if none is present.  Should fix this issue since it won't go for the newest release if there's no binary available yet.

Thanks for opening these issues!  As soon as #6 is merged I'll release a new version on pypi.
