### ISSUE TITLE
Coudn't install solidity 0.4.18 following the wiki instructions.

### ISSUE THREAD

**Issue by ilanDoron** [iamdefinitelyahuman/py-solc-x#84]
### Environment information

* `py-solc-x` Version: 3.2.0
* `solc` Version: 0.4.18
* Python Version: 2.7.16
* OS: osx

### What was wrong?

when running the install file for solc 0.4.18:

brew install https://github.com/ethereum/homebrew-ethereum/blob/2aea171d7d6901b97d5f1f71bd07dd88ed5dfb42/solidity.rb

I get this:

Updating Homebrew...
Warning: Calling Non-checksummed download of solidity formula file from an arbitrary URL is deprecated! Use 'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead.
 -#O#-  #   #                                                                 
Warning: Calling Non-checksummed download of solidity formula file from an arbitrary URL is deprecated! Use 'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead.
 -#O#-  #   #                                                                 
Error: solidity: /Users/iland/Library/Caches/Homebrew/Formula/solidity.rb:6: syntax error, unexpected '<'
<!DOCTYPE html>
^
/Users/iland/Library/Caches/Homebrew/Formula/solidity.rb:7: syntax error, unexpected '<'
<html lang="en">
^
/Users/iland/Library/Caches/Homebrew/Formula/solidity.rb:8: syntax error, unexpected '<'
  <head>
  ^
/Users/iland/Library/Caches/Homebrew/Formula/solidity.rb:10: syntax error, unexpected '<'
  <link rel="dns-prefetch" href=...
  ^
/Users/iland/Library/Caches/Homebrew/Formula/solidity.rb:10: syntax error, unexpected tIDENTIFIER, expecting end-of-input
  <link rel="dns-prefetch" href="https://github.githubassets...
                           ^~~~

so

seems this method is not recommended.
according to output from the run

### How can it be fixed?

Fill this in if you know how the bug could be fixed.

**Comment by iamdefinitelyahuman** [comment]
Unfortunately I'm not using OSX myself and I'm not familiar with Ruby, so I can't be of much help :(

There is a push to serve precompiled solc binaries for OSX - https://github.com/ethereum/solidity/issues/3168  As soon as that happens I'll convert this package to use them, and this problem should become a thing of the past.  In the meantime, I'm really sorry but there's not much I can offer.  Possibly someone in the [solidity gitter](https://gitter.im/ethereum/solidity) will know how to solve it.

**Comment by iamdefinitelyahuman** [comment]
Also related - https://github.com/ethereum/solidity/issues/9226

**Comment by cameel** [comment]
@ilanDoron I think that you're just using a wrong URL. The one you posted is a HTML page that includes the whole Github UI. You cannot execute that as Ruby code - that's why you get errors about "unexpected '<'". You need to use a direct link to the raw file:

https://raw.githubusercontent.com/ethereum/homebrew-ethereum/2aea171d7d6901b97d5f1f71bd07dd88ed5dfb42/solidity.rb

**Comment by iamdefinitelyahuman** [comment]
@cameel good catch! I've updated the wiki to better emphasize this.

**Comment by iamdefinitelyahuman** [comment]
Closing this for now, @ilanDoron if you have further issues feel free to re-open or ping me on gitter.
