### ISSUE TITLE
64 bit arm not supported

### ISSUE THREAD

**Issue by MatthiasLohr** [iamdefinitelyahuman/py-solc-x#86]
### Environment information

* `py-solc-x` Version: 0.10.0
* `solc` Version: 0.6.1
* Python Version: 3.8.2
* OS: Ubuntu (Raspberry Pi, 64 Bit)

### What was wrong?

According to release `v0.10.0`, arm architectures should be supported. However, it seems that this support is only limited to 32 bit arm architectures.

Code is checking for `platform.machine() ^= "arm"`, but on my Raspberry Pi 3 B+ with Ubuntu/64 bit support, `platform.machine()` returns `aarch64`.

**Comment by iamdefinitelyahuman** [comment]
Good catch..  the fix should be as easy as adding a check for `aarch` in `install.py` i think?

https://github.com/iamdefinitelyahuman/py-solc-x/blob/38f767f88f83046358d096f0ec27b60c612cd329/solcx/install.py#L48-L54

I have no way to test this. Would you be willing to fork and make the edit and see if it works as expected? :pray:

**Comment by MatthiasLohr** [comment]
Will do!

**Comment by iamdefinitelyahuman** [comment]
Also worth noting, there is an effort right now to increase the availability of `solc` binaries: https://github.com/ethereum/solidity/issues/9258

This repo is due for a refactor and a new major release, I've been holding off in hopes that osx and arm binaries are made available so these sort of issues become less-so....

**Comment by MatthiasLohr** [comment]
Ok, it's compiling.. since about 30 minutes (and it shows 21%). Compiling on an ARM seems not to be the best idea :D

First thing learned: Maybe binary filenames should be postfixed with architecture. If file `solc-v0.6.5` exists, it will just try to execute it, no matter on which architecture we are now and for which architecture is was built.

**Comment by MatthiasLohr** [comment]
Next thing learned: Don't try it with only 1GB RAM.

**Comment by MatthiasLohr** [comment]
:) What about a release now?

**Comment by iamdefinitelyahuman** [comment]
#89 incoming

**Comment by iamdefinitelyahuman** [comment]
https://github.com/iamdefinitelyahuman/py-solc-x/releases/tag/v0.10.1

thanks for all your help with this release!

**Comment by MatthiasLohr** [comment]
Sure! And thanks for reacting so quickly! Update is already installed, will test now.

**Comment by T3Crypto** [comment]
Downloaded the tar.gz file and ran the "pip install py-solc-x" command on Raspberry Pi 4 terminal. However, the installation is still not successful. May someone please advise as to what steps should be taken? Thank you!
